name: Elisp

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'tools/*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version:
          - 24.1
          - 24.2
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - release-snapshot
        experimental: [false]
        include:
          - emacs_version: snapshot
            experimental: true
          - emacs_version: 24.1
            lint_ignore: 1
          - emacs_version: 24.2
            lint_ignore: 1
        check:
          - load-file
          - byte-compile
          - checkdoc
    env:
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
