name: Elisp

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'tools/*'

jobs:
  build:
    runs-on: macos-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        emacs_version:
          - 28.1
          - 28.2
          - 29.1
          - release-snapshot
        experimental: [false]
        include:
          - emacs_version: snapshot
            experimental: true
    env:
      EMACS_LINT_IGNORE: 0
    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
